- name: Determine the running kernel release
  command: uname -r
  register: kernel_release
  become: yes
  become_method: sudo

- name: Add the WireGuard PPA
  apt_repository:
    repo: 'ppa:wireguard/wireguard'
  become: yes
  become_method: sudo

# Using with_items loop for apt module is deprecated
- name: Install WireGuard and other requirements 
  apt:
    name:
      - linux-headers-{{ kernel_release.stdout }}
      - linux-headers-generic
      - wireguard-dkms
      - wireguard-tools
      - python2.7        
    state: present
    update_cache: true
  become: yes
  become_method: sudo
