- name: Enable IPv4 traffic forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
  become_method: sudo
  tags:
    - wireguard

- name: Enable IPv4 forwarding continued
  command: echo 1 > /proc/sys/net/ipv4/ip_forward
  become: yes
  become_method: sudo
  tags:
    - wireguard

#Set up firewall rules
- name: Track input chain
  iptables:
    chain: INPUT
    match: conntrack
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes
  become_method: sudo
  tags:
    - wireguard

- name: Track forward chain  
  iptables:
    chain: FORWARD
    match: conntrack
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes
  become_method: sudo

- name: Allow incoming wireguard connections    
  iptables:
    chain: INPUT
    protocol: udp
    match: udp
    destination_port: "{{ vpn_port }}"
    ctstate: NEW
    jump: ACCEPT
  become: yes
  become_method: sudo
  tags:
    - wireguard
   
- name: Allow recursive DNS tcp    
  iptables:
    chain: INPUT
    source: "{{ vpn_network }}.0/24"
    protocol: tcp
    match: tcp
    destination_port: 53
    ctstate: NEW
    jump: ACCEPT
  become: yes
  become_method: sudo
  
- name: Allow recursive DNS udp  
  iptables:
    chain: INPUT
    source: "{{ vpn_network }}.0/24"
    protocol: udp
    match: udp
    destination_port: 53
    ctstate: NEW
    jump: ACCEPT
  become: yes
  become_method: sudo
  tags:
    - wireguard
    
- name: Allow forwarding of packets that stay in the tunnel 
  iptables:
    chain: FORWARD
    in_interface: wg0
    match: conntrack
    out_interface: wg0
    ctstate: NEW
    jump: ACCEPT
  become: yes
  become_method: sudo

- name: Set up NAT
  iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ vpn_network }}.0/24"
    out_interface: "{{ ansible_default_ipv4.interface }}"
    jump: MASQUERADE  
  become: yes
  become_method: sudo
  tags:
    - wireguard

- name: Install iptables-persistent
  apt: pkg=iptables-persistent state=present update_cache=true
  become: yes
  become_method: sudo
  tags:
    - wireguard

- name: Set up iptables persistence
  command: netfilter-persistent save
  become: yes
  tags:
    - wireguard


