---
- name: Ensure deps are installed
  apt: 
    name: ["apt-transport-https", "ca-certificates"]
    state: present
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Add Docker apt key.
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Add Docker repository.
  vars:
    docker_apt_arch: amd64
    docker_apt_release_channel: stable
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution| lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Install docker
  apt:
    name: ["docker-ce"]
    state: present
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Enable docker systemd service
  service:
    name: docker
    state: restarted 
    enabled: yes
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Add {{ username }} to docker user group
  shell: usermod -aG docker {{username}}
  become: yes
  become_method: sudo

- name: Install Docker API
  pip:
    name: ['docker', 'jsondiff', 'pyyaml']
    executable: pip2
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Swarm init
  docker_swarm:
    state: present
  become: yes
  become_method: sudo
  ignore_errors: yes
  tags:
    - docker
