---
- name: Install packages
  apt:
    name: ['python3-pip',
          'python-pip',
          'zsh',
          'ufw',
          'vim',
          'neovim-runtime',
          'neovim',
          'curl',
          'nmap',
          'ncdu',
          'git',
          'tmux',
          'sudo'
          ]
    state: present
    update_cache: yes
  become: yes
  become_method: sudo
  tags:
    - common

- name: Upgrade packages
  apt: upgrade=safe
  become: yes
  become_method: sudo
  tags:
    - common
  
