---
- name: Download repo
  git:
    repo: https://gitlab.com/sebohe/dockreth
    dest: "{{ repo_path }}"
    force: yes
  become: yes
  become_method: su
  become_user: "{{ username }}"
  tags:
    - eth-docker

- name: Start stack
  shell: make
  args:
    chdir: "{{ repo_path }}"
  become: yes
  become_method: su
  become_user: "{{ username }}"
  tags:
    - eth-docker

