---
- name: Download repo
  git:
    repo: https://gitlab.com/sebohe/dockreth
    dest: "{{ repo_path }}"
    force: yes
  become: yes
  become_method: su
  become_user: "{{ username }}"
  tags:
    - eth-tests-nets

- name: 
  docker_stack:
    state: present
    name: eth-testnets
    compose:
      - "{{ repo_path }}/docker/ethereums-testnets.yml"
