---
- name: Ensure zsh is the default shell
  user:
    name: "{{ username }}"
    shell: /bin/zsh
    state: present
  become: yes
  become_method: sudo
  tags:
    - root-work-server

- name: Add authorized key
  authorized_key:
    user: "{{ username }}"
    key: "{{lookup('file', public_key) }}"
  become: yes
  become_method: su
  become_user: "{{ username }}"
  tags:
    - root-work-server

- name: Clone dotfiles
  git:
    repo: https://gitlab.com/sebohe/dotfiles 
    dest: "{{ dotfiles }}"
    force: yes
    recursive: no
  become: yes
  become_method: su
  become_user: "{{ username }}"
  tags:
    - root-work-server

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "/home/{{ username }}/.oh-my-zsh"
    force: yes
  become: yes
  become_method: su
  become_user: "{{ username }}"
  tags:
    - root-work-server

- name: Setup dotfiles
  shell: "{{ dotfiles }}/setup.sh"
  args:
    chdir: "{{ dotfiles }}"
  become: yes
  become_method: su
  become_user: "{{ username }}"
  tags:
    - root-work-server

- name: Install nvim plugins
  shell: nvim --headless +PlugInstall +qa
  become: yes
  become_method: su
  become_user: "{{ username }}"
  tags:
    - root-work-server
