---
- name: Download the Go tarball
  get_url:
    url: "{{ go_download_location }}"
    dest: "/usr/local/src/{{ go_tarball }}"
    checksum: "{{ go_tarball_checksum }}"
  become: yes
  become_method: sudo
  tags:
    - go

- name: Register the current Go version (if any)
  command: /usr/lib/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false
  become: yes
  become_method: sudo
  tags:
    - go

- name: Remove old installation of Go
  file:
    path: /usr/local/go
    state: absent
  when: go_version|failed or go_version.stdout != go_version_target
  become: yes
  become_method: sudo
  tags:
    - go

- name: Extract the Go tarball if Go is not yet installed or not the desired version
  unarchive:
    src: /usr/local/src/{{ go_tarball }}
    dest: /usr/local
    copy: no
  when: go_version|failed or go_version.stdout != go_version_target
  become: yes
  become_method: sudo
  tags:
    - go

- name: Add symlink for global to existing path location
  file:
    src: /usr/local/go/bin/go
    path: /usr/local/bin/go
    state: link
  become: yes
  become_method: sudo
  tags:
    - go

- name: Add symlink for global to existing path location
  file:
    src: /usr/local/go/bin/gofmt
    path: /usr/local/bin/gofmt
    state: link
  become: yes
  become_method: sudo
  tags:
    - go
