---
- name: Disable root login
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh

- name: change port number
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?Port"
    line: "Port {{ ssh_port }}"
    state: present
  notify: restart ssh
