---
- name: Enable firewall
  ufw: state=enabled policy=deny
  become: yes
  become_method: sudo
  tags:
    - ufw

- name: Allow HTTP
  ufw: rule=allow port=80 proto=tcp
  become: yes
  become_method: sudo
  tags:
    - ufw

- name: Allow HTTPS
  ufw: rule=allow port=443 proto=tcp
  become: yes
  become_method: sudo
  tags:
    - ufw

- name: Allow SSH
  ufw: "rule=allow port={{ ssh_port }} proto=tcp"
  become: yes
  become_method: sudo
  tags:
    - ufw
